


package com.example.classlink;

import com.google.firebase.database.IgnoreExtraProperties;

@IgnoreExtraProperties
public class ClassNote {
    private String id;            // Firebase push ID (unique key for each note)
    private String title;
    private String subject;
    private String unit;
    private String uploadedBy;
    private long timestamp;
    private String type;          // "text" or "image"
    private String description;   // For text notes
    private String downloadUrl;   // For image notes
    private String aiSummary;     // summary generated by AI/extractive module
    private String estimatedReadTime; // NEW field

    public ClassNote() {
        // Required empty public constructor for Firebase
    }

    // ------------------- Getters -------------------
    public String getId() { return id; }
    public String getTitle() { return title; }
    public String getSubject() { return subject; }
    public String getUnit() { return unit; }
    public String getUploadedBy() { return uploadedBy; }
    public long getTimestamp() { return timestamp; }
    public String getType() { return type; }
    public String getDescription() { return description; }
    public String getDownloadUrl() { return downloadUrl; }
    public String getAiSummary() { return aiSummary; }
    public String getEstimatedReadTime() { return estimatedReadTime; }

    // ------------------- Setters -------------------
    public void setId(String id) { this.id = id; }
    public void setTitle(String title) { this.title = title; }
    public void setSubject(String subject) { this.subject = subject; }
    public void setUnit(String unit) { this.unit = unit; }
    public void setUploadedBy(String uploadedBy) { this.uploadedBy = uploadedBy; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }
    public void setType(String type) { this.type = type; }
    public void setDescription(String description) { this.description = description; }
    public void setDownloadUrl(String downloadUrl) { this.downloadUrl = downloadUrl; }
    public void setAiSummary(String aiSummary) { this.aiSummary = aiSummary; }
    public void setEstimatedReadTime(String estimatedReadTime) { this.estimatedReadTime = estimatedReadTime; }
}

